### ISSUE TITLE
example repo is not accessible 

### ISSUE THREAD

**Issue by dec16180** [outspeed-ai/outspeed#1]
I followed the instructions in https://docs.outspeed.ai/guide/local_development to set up a local instance. However, the example repo seems to be a private repo.

git clone https://github.com/outspeed-ai/examples does not work.

**Comment by janak2** [comment]
@dec16180 Thanks for the issue. We were moving examples around and forgot to update it. Please find the latest docs here: https://docs.outspeed.com/guide/quickstart

The links should be working correctly.
